builds:
  dwait:
    context: /dwait
    dockerfile: Dockerfile
    extract:
        - /go/src/github.com/jizhilong/docker-wait/dwait/bin/.:bin.tar

  dresponse:
    context: /
    dockerfile: dresponse/Dockerfile
    pushes:
        - 'on_branch:master=jizhilong/docker-wait:latest'
        - 'on_tag=jizhilong/docker-wait:{git_tag}'
    depends_on:
      - dwait
