version: "2"
services:
  dresponse:
    build: .
    privileged: true
    command: run_dresponse
    network_mode: host
    volumes:
      - /var/run:/var/run
      - /:/hostroot

  normal-container:
    image: python:2.7.13
    command: echo '33135f5a1fb45f5dff915ec1193c0dc7  /bin/bash'|md5sum -c -
    entrypoint: /d/init
    volumes:
      - /usr/lib/dwait:/d:ro
      - /var/run/dwait:/.dwait:ro
    depends_on:
      - dresponse
