version: "2"
services:
  dresponse:
    build: .
    privileged: true
    command: run_dresponse
    network_mode: host
    volumes:
      - /var/run:/var/run
      - /:/hostroot

  normal-container:
    image: busybox
    command: cat /tmp/hello
    entrypoint: /d/init
    volumes:
      - /usr/lib/dwait:/d:ro
      - /var/run/dwait:/.dwait:ro
    depends_on:
      - dresponse
